ALTER DATABASE DATEFORMAT "mm-dd-yyyy";

CREATE CLASS Ingest_Event IF NOT EXISTS EXTENDS V;

CREATE CLASS Ingest_Entity IF NOT EXISTS EXTENDS V;

CREATE CLASS Address_Normalized IF NOT EXISTS EXTENDS V;

CREATE CLASS Agent IF NOT EXISTS EXTENDS V;

CREATE CLASS Address_Has_Coordinates IF NOT EXISTS EXTENDS E;

CREATE CLASS Address_Provided_Normalized IF NOT EXISTS EXTENDS E;

CREATE CLASS Address_Provided_Geocoded IF NOT EXISTS EXTENDS E;

CREATE CLASS Bank_Account IF NOT EXISTS EXTENDS V;

CREATE CLASS Bank_Account_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Clerk IF NOT EXISTS EXTENDS V;

CREATE CLASS Clerk_Conducting_Transaction IF NOT EXISTS EXTENDS E;

CREATE CLASS Company_Customer_ID IF NOT EXISTS EXTENDS V;

CREATE CLASS Company_Customer_ID_Captured IF NOT EXISTS EXTENDS E;

CREATE CLASS Company_Loyalty_Number IF NOT EXISTS EXTENDS V;

CREATE CLASS Credit_Card IF NOT EXISTS EXTENDS V;

CREATE CLASS Credit_Card_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Date_Of_Birth IF NOT EXISTS EXTENDS V;

CREATE CLASS Date_Of_Birth_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Device_Used_During_Transaction IF NOT EXISTS EXTENDS E;

CREATE CLASS Electronic_Device IF NOT EXISTS EXTENDS V;

CREATE CLASS Email IF NOT EXISTS EXTENDS V;

CREATE CLASS Email_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS GEO_Code_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Geocode IF NOT EXISTS EXTENDS V;

CREATE CLASS Has_Transaction_Record IF NOT EXISTS EXTENDS E;

CREATE CLASS Has_Name_Segment IF NOT EXISTS EXTENDS E;

CREATE CLASS IP_Address IF NOT EXISTS EXTENDS V;

CREATE CLASS IP_Address_During_Transaction IF NOT EXISTS EXTENDS E;

CREATE CLASS Identification_Number IF NOT EXISTS EXTENDS V;

CREATE CLASS Identification_Provided IF NOT EXISTS EXTENDS E;

/* CREATE CLASS KeyWord IF NOT EXISTS EXTENDS V; */

CREATE CLASS Loyalty_Number_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Agent_Conducting_Transaction IF NOT EXISTS EXTENDS E;

CREATE CLASS MSB_Clerk IF NOT EXISTS EXTENDS Ingest_Entity, V;

CREATE CLASS MSB_Agent IF NOT EXISTS EXTENDS Ingest_Entity, V;

CREATE CLASS MSB_On_Behalf_Sender_Transaction IF NOT EXISTS EXTENDS E;

CREATE CLASS MSB_Payee_Agent_Entity IF NOT EXISTS EXTENDS MSB_Agent, V;

CREATE CLASS MSB_Payee_Entity IF NOT EXISTS EXTENDS Ingest_Entity, V;

CREATE CLASS MSB_Sender_Agent_Entity IF NOT EXISTS EXTENDS MSB_Agent, V;

CREATE CLASS MSB_Sender_Entity IF NOT EXISTS EXTENDS Ingest_Entity, V;

CREATE CLASS MSB_Sender_On_Behalf_Of_Entity IF NOT EXISTS EXTENDS Ingest_Entity, V;

CREATE CLASS MSB_Transaction IF NOT EXISTS EXTENDS V;

CREATE CLASS MSB_Transaction_Payee IF NOT EXISTS EXTENDS E;

CREATE CLASS MSB_Transaction_Payee_Agent IF NOT EXISTS EXTENDS E;

CREATE CLASS MSB_Transaction_Sender IF NOT EXISTS EXTENDS E;

CREATE CLASS MSB_Transaction_Sender_Agent IF NOT EXISTS EXTENDS E;

CREATE CLASS Name IF NOT EXISTS EXTENDS V;

CREATE CLASS Name_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Name_Segment IF NOT EXISTS EXTENDS V;

CREATE CLASS Name_Segment_Provided IF NOT EXISTS EXTENDS E;

/*
CREATE CLASS OFunction IF NOT EXISTS;

CREATE CLASS OGeometryCollection IF NOT EXISTS EXTENDS OShape;

CREATE CLASS OIdentity IF NOT EXISTS;

CREATE CLASS OLineString IF NOT EXISTS EXTENDS OShape;

CREATE CLASS OMultiLineString IF NOT EXISTS EXTENDS OShape;

CREATE CLASS OMultiPoint IF NOT EXISTS EXTENDS OShape;

CREATE CLASS OMultiPolygon IF NOT EXISTS EXTENDS OShape;

CREATE CLASS OPoint IF NOT EXISTS EXTENDS OShape;

CREATE CLASS OPolygon IF NOT EXISTS EXTENDS OShape;

CREATE CLASS ORectangle IF NOT EXISTS EXTENDS OShape;

CREATE CLASS ORestricted IF NOT EXISTS;

CREATE CLASS ORole IF NOT EXISTS EXTENDS OIdentity;

CREATE CLASS OSchedule IF NOT EXISTS;

CREATE CLASS OSequence IF NOT EXISTS;

CREATE CLASS OShape IF NOT EXISTS;

CREATE CLASS OTriggered IF NOT EXISTS;

CREATE CLASS OUser IF NOT EXISTS EXTENDS OIdentity;
*/

CREATE CLASS Occupation IF NOT EXISTS EXTENDS V;

CREATE CLASS Occupation_Provided IF NOT EXISTS EXTENDS E;

CREATE CLASS Phone_Normalized IF NOT EXISTS EXTENDS V;

CREATE CLASS Phone_Provided_Normalized IF NOT EXISTS EXTENDS E;

CREATE CLASS Provided_By IF NOT EXISTS EXTENDS E;

/* CREATE CLASS SearchEvent IF NOT EXISTS EXTENDS V;*/

/* CREATE CLASS Searched IF NOT EXISTS EXTENDS E;

CREATE CLASS URL IF NOT EXISTS EXTENDS V;
CREATE CLASS V IF NOT EXISTS;
CREATE CLASS _studio IF NOT EXISTS;
CREATE CLASS based_in IF NOT EXISTS EXTENDS E; */

/* CREATE CLASS categorized IF NOT EXISTS EXTENDS E;

CREATE CLASS categorized_as IF NOT EXISTS EXTENDS E;

CREATE CLASS category IF NOT EXISTS EXTENDS V;
CREATE CLASS contains_email IF NOT EXISTS EXTENDS E;

CREATE CLASS contains_phone IF NOT EXISTS EXTENDS E;

CREATE CLASS country IF NOT EXISTS EXTENDS V;
CREATE CLASS domain IF NOT EXISTS EXTENDS V;
CREATE CLASS domain_is IF NOT EXISTS EXTENDS E;

CREATE CLASS hyperlink_to IF NOT EXISTS EXTENDS E;

CREATE CLASS registrant IF NOT EXISTS EXTENDS V;
CREATE CLASS registrant_is IF NOT EXISTS EXTENDS E;

CREATE CLASS suggested IF NOT EXISTS EXTENDS E; */

CREATE PROPERTY Address_Normalized.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Address_Normalized.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Address_Normalized.Full_Address_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.Street_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.Line1_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.Line2_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.City_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.State_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.Postal_Code_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.Country_Clean IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.HSI_AOR IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.in_Address_Provided IF NOT EXISTS LINKLIST Address_Provided_Normalized;
CREATE PROPERTY Address_Normalized.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Address_Normalized.Longitude IF NOT EXISTS FLOAT;
CREATE PROPERTY Address_Normalized.Latitude IF NOT EXISTS FLOAT;
CREATE PROPERTY Address_Normalized.in_Address_Provided_Normalized IF NOT EXISTS LINKLIST Address_Provided_Normalized;
CREATE PROPERTY Address_Normalized.out_Address_Has_Coordinates IF NOT EXISTS LINKLIST Address_Has_Coordinates;

CREATE PROPERTY Address_Has_Coordinates.in IF NOT EXISTS LINK Geocode;
CREATE PROPERTY Address_Has_Coordinates.out IF NOT EXISTS LINK Address_Normalized;

CREATE PROPERTY Address_Provided_Normalized.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Address_Provided_Normalized.in IF NOT EXISTS LINK Address_Normalized;

CREATE PROPERTY Address_Provided_Geocoded.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Address_Provided_Geocoded.in IF NOT EXISTS LINK Geocode;

CREATE PROPERTY Agent.Add_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY Agent.Add_User IF NOT EXISTS STRING;
CREATE PROPERTY Agent.Agent_Number IF NOT EXISTS STRING;
CREATE PROPERTY Agent.Agent_Type IF NOT EXISTS STRING;
CREATE PROPERTY Agent.Agent_Name IF NOT EXISTS STRING;
CREATE PROPERTY Agent.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Agent.in_Agent_Conducting_Transaction IF NOT EXISTS LINKLIST Agent_Conducting_Transaction;

CREATE PROPERTY Clerk.Add_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Add_User IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Clerk_Number IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Agent_Type IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Agent_Name IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Agent_Clerk IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.in_Clerk_Conducting_Transaction IF NOT EXISTS LINKLIST Clerk_Conducting_Transaction;

CREATE PROPERTY Bank_Account.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Bank_Account.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Bank_Account.Bank_Account_Look_Up IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Account_Exclude IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Account_Number IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Account_Type IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Account_Holder_Name IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Name IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Identification_Code IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Routing_Number IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Internal_Customer_ID IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_ID IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Other_Bank_Code IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_City IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Branch_Code IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Branch_Name IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.Bank_Card_IIN IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.BIC IF NOT EXISTS STRING;
CREATE PROPERTY Bank_Account.in_Bank_Account_Provided IF NOT EXISTS LINKLIST Bank_Account_Provided;

CREATE PROPERTY Bank_Account_Provided.in IF NOT EXISTS LINK Bank_Account;
CREATE PROPERTY Bank_Account_Provided.out IF NOT EXISTS LINK Ingest_Entity;

CREATE PROPERTY Clerk_Conducting_Transaction.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Clerk_Conducting_Transaction.in IF NOT EXISTS LINK Clerk;

CREATE PROPERTY Company_Customer_ID.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Company_Customer_ID.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Company_Customer_ID.Company_Customer_ID IF NOT EXISTS STRING;
CREATE PROPERTY Company_Customer_ID.Customer_ID_Look_Up IF NOT EXISTS STRING;
CREATE PROPERTY Company_Customer_ID.Online_Customer_Flag IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Company_Customer_ID.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Company_Customer_ID.in_Company_Customer_ID_Captured IF NOT EXISTS LINKLIST Company_Customer_ID_Captured;

CREATE PROPERTY Company_Customer_ID_Captured.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Company_Customer_ID_Captured.in IF NOT EXISTS LINK Company_Customer_ID;

CREATE PROPERTY Company_Loyalty_Number.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Company_Loyalty_Number.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Company_Loyalty_Number.Card_Number IF NOT EXISTS STRING;
CREATE PROPERTY Company_Loyalty_Number.Company IF NOT EXISTS STRING;
CREATE PROPERTY Company_Loyalty_Number.Loyalty_Card_Exclude IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Company_Loyalty_Number.Loyalty_Card_Look_Up IF NOT EXISTS STRING;
CREATE PROPERTY Company_Loyalty_Number.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Company_Loyalty_Number.in_Loyalty_Number_Provided IF NOT EXISTS LINKLIST Loyalty_Number_Provided;

CREATE PROPERTY Loyalty_Number_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Loyalty_Number_Provided.in IF NOT EXISTS LINK Company_Loyalty_Number;

CREATE PROPERTY Credit_Card.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Credit_Card.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Credit_Card.Card_Number IF NOT EXISTS STRING;
CREATE PROPERTY Credit_Card.Credit_Card_Exclude IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Credit_Card.in_Credit_Card_Provided IF NOT EXISTS LINKLIST Credit_Card_Provided;
CREATE PROPERTY Credit_Card.UUID IF NOT EXISTS STRING;

CREATE PROPERTY Credit_Card_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Credit_Card_Provided.in IF NOT EXISTS LINK Credit_Card;

CREATE PROPERTY Date_Of_Birth.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Date_Of_Birth.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Date_Of_Birth.DOB IF NOT EXISTS STRING;
CREATE PROPERTY Date_Of_Birth.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Date_Of_Birth.in_Date_Of_Birth_Provided IF NOT EXISTS LINKLIST Date_Of_Birth_Provided;
CREATE PROPERTY Date_Of_Birth.Date_Of_Birth_Clean IF NOT EXISTS STRING;

CREATE PROPERTY Date_Of_Birth_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Date_Of_Birth_Provided.in IF NOT EXISTS LINK Date_Of_Birth;

CREATE PROPERTY Device_Used_During_Transaction.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Device_Used_During_Transaction.in IF NOT EXISTS LINK Electronic_Device;

CREATE PROPERTY Electronic_Device.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Electronic_Device.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Electronic_Device.Description IF NOT EXISTS STRING;
CREATE PROPERTY Electronic_Device.Exclude IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Electronic_Device.Operating_System IF NOT EXISTS STRING;
CREATE PROPERTY Electronic_Device.Device_ID IF NOT EXISTS STRING;
CREATE PROPERTY Electronic_Device.UUID IF NOT EXISTS STRING;

CREATE PROPERTY Email.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Email.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Email.Email IF NOT EXISTS STRING;
CREATE PROPERTY Email.Exclude IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Email.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Email.in_Email_Provided IF NOT EXISTS LINKLIST Email_Provided;

CREATE PROPERTY Email_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Email_Provided.in IF NOT EXISTS LINK Email;

CREATE PROPERTY GEO_Code_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY GEO_Code_Provided.in IF NOT EXISTS LINK Geocode;

CREATE PROPERTY Geocode.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Geocode.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Geocode.Coordinates IF NOT EXISTS STRING;
CREATE PROPERTY Geocode.Latitude IF NOT EXISTS STRING;
CREATE PROPERTY Geocode.Longitude IF NOT EXISTS STRING;
CREATE PROPERTY Geocode.Source IF NOT EXISTS STRING;
CREATE PROPERTY Geocode.in_Address_Provided_Geocoded IF NOT EXISTS LINKLIST Address_Provided_Geocoded;
CREATE PROPERTY Geocode.in_Address_Has_Coordinates IF NOT EXISTS LINKLIST Address_Has_Coordinates;

CREATE PROPERTY Has_Transaction_Record.in IF NOT EXISTS LINK MSB_Transaction;
CREATE PROPERTY Has_Transaction_Record.out IF NOT EXISTS LINK Ingest_Event;

CREATE PROPERTY Has_Name_Segment.in IF NOT EXISTS LINK Name_Segment;
CREATE PROPERTY Has_Name_Segment.out IF NOT EXISTS LINK Name;

CREATE PROPERTY IP_Address.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY IP_Address.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY IP_Address.Address IF NOT EXISTS STRING;
CREATE PROPERTY IP_Address.Exclude IF NOT EXISTS BOOLEAN;
CREATE PROPERTY IP_Address.UUID IF NOT EXISTS STRING;
CREATE PROPERTY IP_Address.in_IP_Address_During_Transaction IF NOT EXISTS LINKLIST IP_Address_During_Transaction;

CREATE PROPERTY IP_Address_During_Transaction.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY IP_Address_During_Transaction.in IF NOT EXISTS LINK IP_Address;

CREATE PROPERTY Identification_Number.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Identification_Number.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Identification_Number.Country IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.Description IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.Exclude IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Identification_Number.ID_Number IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.Location IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.Look_Up IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.State IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.Type IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Identification_Number.in_Identification_Provided IF NOT EXISTS LINKLIST Identification_Provided;

CREATE PROPERTY Identification_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Identification_Provided.in IF NOT EXISTS LINK Identification_Number;

/* CREATE PROPERTY KeyWord.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY KeyWord.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE); */

CREATE PROPERTY MSB_Agent.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY MSB_Agent.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY MSB_Agent.Agent_Name IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Agent.Agent_Number IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Agent.Agent_Type IF NOT EXISTS STRING;

CREATE PROPERTY MSB_Agent.in_MSB_Transaction_Payee_Agent IF NOT EXISTS LINKLIST MSB_Transaction_Payee_Agent;
CREATE PROPERTY MSB_Agent.out_MSB_Transaction_Sender_Agent IF NOT EXISTS LINKLIST MSB_Transaction_Sender_Agent;
CREATE PROPERTY MSB_Agent.out_Agent_Conducting_Transaction IF NOT EXISTS LINKLIST Agent_Conducting_Transaction;
CREATE PROPERTY MSB_Agent.out_Clerk_Conducting_Transaction IF NOT EXISTS LINKLIST Clerk_Conducting_Transaction;
CREATE PROPERTY MSB_Agent.out_Phone_Provided_Normalized IF NOT EXISTS LINKLIST Phone_Provided_Normalized;
CREATE PROPERTY MSB_Agent.out_Address_Provided_Normalized IF NOT EXISTS LINKLIST Address_Provided_Normalized;
CREATE PROPERTY MSB_Agent.out_Address_Provided_Geocoded IF NOT EXISTS LINKLIST Address_Provided_Geocoded;
CREATE PROPERTY MSB_Agent.out_Agent_Conducting_Transaction IF NOT EXISTS LINKLIST Agent_Conducting_Transaction;
CREATE PROPERTY MSB_Agent.out_Clerk_Conducting_Transaction IF NOT EXISTS LINKLIST Clerk_Conducting_Transaction;

CREATE PROPERTY Agent_Conducting_Transaction.in IF NOT EXISTS LINK Agent;
CREATE PROPERTY Agent_Conducting_Transaction.out IF NOT EXISTS LINK Ingest_Entity;

CREATE PROPERTY Clerk.Add_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Clerk.Agent_Name IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Agent_Number IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Agent_Type IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Clerk IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.Add_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY Clerk.in_Clerk_Conducting_Transaction IF NOT EXISTS LINKLIST MSB_Clerk_Conducting_Transaction;

CREATE PROPERTY Ingest_Entity.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Ingest_Entity.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Ingest_Entity.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Entity.out_MSB_Transaction_Sender IF NOT EXISTS LINKLIST MSB_Transaction_Sender;
CREATE PROPERTY Ingest_Entity.out_Name_Provided IF NOT EXISTS LINKLIST Name_Provided;
CREATE PROPERTY Ingest_Entity.out_Address_Provided_Normalized IF NOT EXISTS LINKLIST Address_Provided_Normalized;
CREATE PROPERTY Ingest_Entity.out_Address_Provided_Geocoded IF NOT EXISTS LINKLIST Address_Provided_Geocoded;
CREATE PROPERTY Ingest_Entity.out_Date_Of_Birth_Provided IF NOT EXISTS LINKLIST Date_Of_Birth_Provided;
CREATE PROPERTY Ingest_Entity.out_Phone_Provided_Normalized IF NOT EXISTS LINKLIST Phone_Provided_Normalized;
CREATE PROPERTY Ingest_Entity.out_Company_Customer_ID_Captured IF NOT EXISTS LINKLIST Company_Customer_ID_Captured;
CREATE PROPERTY Ingest_Entity.out_Credit_Card_Provided IF NOT EXISTS LINKLIST Credit_Card_Provided;
CREATE PROPERTY Ingest_Entity.out_Occupation_Provided IF NOT EXISTS LINKLIST Occupation_Provided;
CREATE PROPERTY Ingest_Entity.out_Loyalty_Number_Provided IF NOT EXISTS LINKLIST Loyalty_Number_Provided;
CREATE PROPERTY Ingest_Entity.out_Bank_Account_Provided IF NOT EXISTS LINKLIST Bank_Account_Provided;
CREATE PROPERTY Ingest_Entity.out_Identification_Provided IF NOT EXISTS LINKLIST Identification_Provided;
CREATE PROPERTY Ingest_Entity.out_IP_Address_During_Transaction IF NOT EXISTS LINKLIST IP_Address_During_Transaction;
CREATE PROPERTY Ingest_Entity.out_Email_Provided IF NOT EXISTS LINKLIST Email_Provided;
CREATE PROPERTY Ingest_Entity.out_Clerk_Conducting_Transaction IF NOT EXISTS LINKLIST Clerk_Conducting_Transaction;
CREATE PROPERTY Ingest_Entity.out_Agent_Conducting_Transaction IF NOT EXISTS LINKLIST Agent_Conducting_Transaction;

CREATE PROPERTY Ingest_Event.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Ingest_Event.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Ingest_Event.Source_Type IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Source_Description IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Record_Owner_Operation_Name IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Record_Owner_Case_Number IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Record_Owner_User IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Record_Owner_Grand_Jury_Number IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Disclosure_Instructions IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.Restrictions_Flag IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Ingest_Event.Company IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Ingest_Event.out_Has_Transaction_Record IF NOT EXISTS LINKLIST Has_Transaction_Record;

CREATE PROPERTY MSB_Payee_Entity.in_MSB_Transaction_Payee IF NOT EXISTS LINKLIST MSB_Transaction_Payee;

CREATE PROPERTY MSB_On_Behalf_Sender_Transaction.out IF NOT EXISTS LINK MSB_Sender_On_Behalf_Of_Entity;
CREATE PROPERTY MSB_On_Behalf_Sender_Transaction.in IF NOT EXISTS LINK MSB_Transaction;

CREATE PROPERTY MSB_Sender_Entity.out_MSB_Transaction_Sender IF NOT EXISTS LINKLIST MSB_Transaction_Sender;

CREATE PROPERTY MSB_Sender_On_Behalf_Of_Entity.out_MSB_On_Behalf_Sender_Transaction IF NOT EXISTS LINKLIST MSB_On_Behalf_Sender_Transaction;

CREATE PROPERTY MSB_Transaction.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY MSB_Transaction.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY MSB_Transaction.UUID IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Disclosure_Instructions IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Restrictions_Flag IF NOT EXISTS BOOLEAN;
CREATE PROPERTY MSB_Transaction.Send_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Pay_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Cancelled_Date_Time IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Send_Amount_USD IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Pay_Amount_USD IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Refund_Code IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Sender_Fee_Local IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Sender_Face_Local IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Sender_Currency IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Sender_Fee_USD IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Sender_Total_Amount IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Payee_Face_Local IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Payee_Currency IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Transaction_Status IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Transaction_Type IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Aggregator_Confirmation_Number IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.First_Transaction_Load_Date IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Last_Transaction_Load_Date IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Send_Date_Time_Clean IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Company IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Company_Number IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Payee_Amount_USD_Clean IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Pay_Date_Time_Clean IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Sender_Payment_Method IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Transaction_Look_Up IF NOT EXISTS STRING;
CREATE PROPERTY MSB_Transaction.Sender_Amount_USD_Clean IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.Payee_Total_Amount IF NOT EXISTS FLOAT;
CREATE PROPERTY MSB_Transaction.in_Has_Transaction_Record IF NOT EXISTS LINKLIST Has_Transaction_Record;
CREATE PROPERTY MSB_Transaction.in_MSB_Transaction_Sender IF NOT EXISTS LINKLIST MSB_Transaction_Sender;
CREATE PROPERTY MSB_Transaction.out_MSB_Transaction_Payee IF NOT EXISTS LINKLIST MSB_Transaction_Payee;
CREATE PROPERTY MSB_Transaction.out_MSB_On_Behalf_Sender_Transaction IF NOT EXISTS LINKLIST MSB_On_Behalf_Sender_Transaction;
CREATE PROPERTY MSB_Transaction.in_MSB_On_Behalf_Sender_Transaction IF NOT EXISTS LINKLIST MSB_On_Behalf_Sender_Transaction;
CREATE PROPERTY MSB_Transaction.in_MSB_Transaction_Sender_Agent IF NOT EXISTS LINKLIST MSB_Transaction_Sender_Agent;
CREATE PROPERTY MSB_Transaction.out_MSB_Transaction_Payee_Agent IF NOT EXISTS LINKLIST MSB_Transaction_Payee_Agent;

CREATE PROPERTY MSB_Transaction_Payee.in IF NOT EXISTS LINK MSB_Payee_Entity;
CREATE PROPERTY MSB_Transaction_Payee.out IF NOT EXISTS LINK MSB_Transaction;

CREATE PROPERTY MSB_Transaction_Payee_Agent.in IF NOT EXISTS LINK MSB_Payee_Agent_Entity;
CREATE PROPERTY MSB_Transaction_Payee_Agent.out IF NOT EXISTS LINK MSB_Transaction;

CREATE PROPERTY MSB_Transaction_Sender.out IF NOT EXISTS LINK MSB_Sender_Entity;
CREATE PROPERTY MSB_Transaction_Sender.in IF NOT EXISTS LINK MSB_Transaction;

CREATE PROPERTY MSB_Transaction_Sender_Agent.out IF NOT EXISTS LINK MSB_Sender_Agent_Entity;
CREATE PROPERTY MSB_Transaction_Sender_Agent.in IF NOT EXISTS LINK MSB_Transaction;

CREATE PROPERTY Name.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Name.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Name.Clean_First_Last_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_First_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_Full_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_Gender IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_Middle_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_Prefix IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_Second_Last_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Clean_Suffix IF NOT EXISTS STRING;
CREATE PROPERTY Name.Company_Name_Flag IF NOT EXISTS BOOLEAN;
CREATE PROPERTY Name.First_Last_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.First_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Middle_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.Second_Last_Name IF NOT EXISTS STRING;
CREATE PROPERTY Name.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Name.in_Name_Provided IF NOT EXISTS LINKLIST Name_Provided;

CREATE PROPERTY Name_Provided.in IF NOT EXISTS LINK Name;
CREATE PROPERTY Name_Provided.out IF NOT EXISTS LINK Ingest_Entity;

CREATE PROPERTY Name_Segment.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Name_Segment.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Name_Segment.Name IF NOT EXISTS STRING;

CREATE PROPERTY Name_Segment_Provided.in IF NOT EXISTS LINK Name_Segment;
CREATE PROPERTY Name_Segment_Provided.out IF NOT EXISTS LINK Name;

/* CREATE PROPERTY OFunction.code IF NOT EXISTS STRING; */

















CREATE PROPERTY Occupation.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Occupation.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Occupation.Occupation IF NOT EXISTS STRING;
CREATE PROPERTY Occupation.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Occupation.in_Occupation_Provided IF NOT EXISTS LINKLIST Occupation_Provided;

CREATE PROPERTY Occupation_Provided.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Occupation_Provided.in IF NOT EXISTS LINK Occupation;

CREATE PROPERTY Phone_Normalized.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Phone_Normalized.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Phone_Normalized.E164 IF NOT EXISTS STRING;
CREATE PROPERTY Phone_Normalized.Country IF NOT EXISTS STRING;
CREATE PROPERTY Phone_Normalized.UUID IF NOT EXISTS STRING;
CREATE PROPERTY Phone_Normalized.in_Phone_Provided_Normalized IF NOT EXISTS LINKLIST Phone_Provided_Normalized;

CREATE PROPERTY Phone_Provided_Normalized.out IF NOT EXISTS LINK Ingest_Entity;
CREATE PROPERTY Phone_Provided_Normalized.in IF NOT EXISTS LINK Phone_Normalized;

/* CREATE PROPERTY Provided_By.out IF NOT EXISTS LINK;

CREATE PROPERTY SearchEvent.Add_Date_Time IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY SearchEvent.Add_User IF NOT EXISTS STRING (MANDATORY TRUE, NOTNULL TRUE);

CREATE PROPERTY Searched.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY based_in.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY categorized.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY categorized_as.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY contains_email.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY contains_phone.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY domain_is.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY hyperlink_to.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY registrant_is.Add_User IF NOT EXISTS STRING;

CREATE PROPERTY suggested.Add_User IF NOT EXISTS STRING; */

ALTER CLASS Ingest_Event STRICTMODE TRUE;

ALTER CLASS Ingest_Entity STRICTMODE TRUE;

ALTER CLASS Address_Normalized STRICTMODE TRUE;

ALTER CLASS Agent STRICTMODE TRUE;

ALTER CLASS Address_Has_Coordinates STRICTMODE TRUE;

ALTER CLASS Address_Provided_Normalized STRICTMODE TRUE;

ALTER CLASS Address_Provided_Geocoded STRICTMODE TRUE;

ALTER CLASS Bank_Account STRICTMODE TRUE;

ALTER CLASS Bank_Account_Provided STRICTMODE TRUE;

ALTER CLASS Clerk STRICTMODE TRUE;

ALTER CLASS Clerk_Conducting_Transaction STRICTMODE TRUE;

ALTER CLASS Company_Customer_ID STRICTMODE TRUE;

ALTER CLASS Company_Customer_ID_Captured STRICTMODE TRUE;

ALTER CLASS Company_Loyalty_Number STRICTMODE TRUE;

ALTER CLASS Credit_Card STRICTMODE TRUE;

ALTER CLASS Credit_Card_Provided STRICTMODE TRUE;

ALTER CLASS Date_Of_Birth STRICTMODE TRUE;

ALTER CLASS Date_Of_Birth_Provided STRICTMODE TRUE;

ALTER CLASS Device_Used_During_Transaction STRICTMODE TRUE;

ALTER CLASS Electronic_Device STRICTMODE TRUE;

ALTER CLASS Email STRICTMODE TRUE;

ALTER CLASS Email_Provided STRICTMODE TRUE;

ALTER CLASS GEO_Code_Provided STRICTMODE TRUE;

ALTER CLASS Geocode STRICTMODE TRUE;

ALTER CLASS Has_Transaction_Record STRICTMODE TRUE;

ALTER CLASS Has_Name_Segment STRICTMODE TRUE;

ALTER CLASS IP_Address STRICTMODE TRUE;

ALTER CLASS IP_Address_During_Transaction STRICTMODE TRUE;

ALTER CLASS Identification_Number STRICTMODE TRUE;

ALTER CLASS Identification_Provided STRICTMODE TRUE;

/* ALTER CLASS KeyWord STRICTMODE TRUE; */

ALTER CLASS Loyalty_Number_Provided STRICTMODE TRUE;

ALTER CLASS Agent STRICTMODE TRUE;

ALTER CLASS Agent_Conducting_Transaction STRICTMODE TRUE;

ALTER CLASS Clerk STRICTMODE TRUE;

ALTER CLASS Ingest_Event STRICTMODE TRUE;

ALTER CLASS MSB_On_Behalf_Sender_Transaction STRICTMODE TRUE;

ALTER CLASS MSB_Payee_Agent_Entity STRICTMODE TRUE;

ALTER CLASS MSB_Payee_Entity STRICTMODE TRUE;

ALTER CLASS MSB_Sender_Agent_Entity STRICTMODE TRUE;

ALTER CLASS MSB_Sender_Entity STRICTMODE TRUE;

ALTER CLASS MSB_Sender_On_Behalf_Of_Entity STRICTMODE TRUE;

ALTER CLASS MSB_Transaction STRICTMODE TRUE;

ALTER CLASS MSB_Transaction_Payee STRICTMODE TRUE;

ALTER CLASS MSB_Transaction_Payee_Agent STRICTMODE TRUE;

ALTER CLASS MSB_Transaction_Sender STRICTMODE TRUE;

ALTER CLASS MSB_Transaction_Sender_Agent STRICTMODE TRUE;

ALTER CLASS Name STRICTMODE TRUE;

ALTER CLASS Name_Provided STRICTMODE TRUE;

ALTER CLASS Name_Segment STRICTMODE TRUE;

ALTER CLASS Name_Segment_Provided STRICTMODE TRUE;

ALTER CLASS Occupation STRICTMODE TRUE;

ALTER CLASS Occupation_Provided STRICTMODE TRUE;

ALTER CLASS Phone_Normalized STRICTMODE TRUE;

ALTER CLASS Phone_Provided_Normalized STRICTMODE TRUE;

/* ALTER CLASS Provided_By STRICTMODE TRUE;

ALTER CLASS SearchEvent STRICTMODE TRUE;

ALTER CLASS Searched STRICTMODE TRUE;

ALTER CLASS URL STRICTMODE TRUE;
ALTER CLASS _studio STRICTMODE TRUE;
ALTER CLASS based_in STRICTMODE TRUE;

ALTER CLASS categorized STRICTMODE TRUE;

ALTER CLASS categorized_as STRICTMODE TRUE;

ALTER CLASS category STRICTMODE TRUE;
ALTER CLASS contains_email STRICTMODE TRUE;

ALTER CLASS contains_phone STRICTMODE TRUE;

ALTER CLASS country STRICTMODE TRUE;
ALTER CLASS domain STRICTMODE TRUE;
ALTER CLASS domain_is STRICTMODE TRUE;

ALTER CLASS hyperlink_to STRICTMODE TRUE;

ALTER CLASS registrant STRICTMODE TRUE;
ALTER CLASS registrant_is STRICTMODE TRUE;

ALTER CLASS suggested STRICTMODE TRUE; */

CREATE INDEX MSB_Transaction.Transaction_Look_Up FULLTEXT;

CREATE INDEX Ingest_Event.UUID FULLTEXT;

CREATE INDEX Ingest_Entity.UUID FULLTEXT;

CREATE INDEX Name.Clean_Full_Name FULLTEXT;

CREATE INDEX Address_Normalized.Full_Address_Clean FULLTEXT;

CREATE INDEX Geocode.Latitude FULLTEXT;
CREATE INDEX Geocode.Longitude FULLTEXT;

CREATE INDEX Date_Of_Birth.Date_Of_Birth_Clean FULLTEXT;

CREATE INDEX Phone_Normalized.E164 FULLTEXT;

CREATE INDEX Company_Customer_ID.Company_Customer_ID FULLTEXT;

CREATE INDEX Credit_Card.Card_Number FULLTEXT;

CREATE INDEX Occupation.Occupation FULLTEXT;

CREATE INDEX Company_Loyalty_Number.Loyalty_Card_Look_Up FULLTEXT;

CREATE INDEX Bank_Account.Bank_Account_Look_Up FULLTEXT;

CREATE INDEX Identification_Number.ID_Number FULLTEXT;

CREATE INDEX IP_Address.Address FULLTEXT;

CREATE INDEX Electronic_Device.Device_ID FULLTEXT;

CREATE INDEX Email.Email FULLTEXT;

CREATE INDEX Agent.Agent_Number FULLTEXT;

CREATE INDEX Clerk.Agent_Clerk FULLTEXT;
